### ISSUE TITLE
AttributeError: 'Custom' object has no attribute 'track_refine'

### ISSUE THREAD

**Issue by yuanbowu** [foolwood/SiamMask#116]
I  run on the command line sucessfully
but when I run on PyCharm 
it appear 

[Warning] unused_pretrained_keys: {'refine_model.h0.2.bias', 'refine_model.h2.2.weight', 'refine_model.v2.2.weight', 'refine_model.post2.bias', 'refine_model.v2.0.weight', 'refine_model.v0.2.bias', '

AttributeError: 'Custom' object has no attribute 'track_refine'
how can I solve it?
thank you

**Comment by ShihuaiXu** [comment]
have you slove this problem？
