### ISSUE TITLE
AttributeError: 'Custom' object has no attribute 'track_refine'

### ISSUE THREAD

**Issue by ks322181** [foolwood/SiamMask#126]
AttributeError: 'Custom' object has no attribute 'track_refine'

python ../../tools/demo.py --resume SiamMask_DAVIS.pth --config config_davis.json

When i am running the above command . It is displaying an images but when i am selecting (ROI) in  image. It is throwing the above error. How to resolve this.

Thanks in Advance

**Comment by skh0619** [comment]
I have same error for test

**Comment by SamihaSara** [comment]
@ks322181 did you solve this issue?
