### ISSUE TITLE
ZeroDivisionError: divide by zero error when tried a smaller batch size in Testing

### ISSUE THREAD

**Issue by SamihaSara** [foolwood/SiamMask#133]
I tried to see the testing results in my laptop with only bag and ball1. For this I only kept these two files in 
/home/samiha/SiamMask/experiments/siammask_sharp/test/VOT2016/Custom_mask_refine_SiamMask_VOT/VOT2016
and in 
/home/samiha/SiamMask/data/VOT2016; but I am facing a ZeroDivisionError as bellow. Please help with suggestions to solve this.

![image](https://user-images.githubusercontent.com/9627710/71229755-0693ff00-2311-11ea-9b62-ac5c3c0486ad.png)

**Comment by liuwenbo4795** [comment]
The problem I face is a little different. I have tested the vot2018 dataset,whe I run the following  Statement to show the result table ,"python ../../tools/eval.py --dataset VOT2018 --tracker_prefix C --result_dir ./test/VOT2018",I meet the ZeroDivisionError: division by zero.I don't know how to solve it!

**Comment by SamihaSara** [comment]
Though I have not tried it yet, also it is not the same problem as ours, could you please try this solution to see if it also works in this case?
Link-- https://github.com/foolwood/SiamMask/issues/143#issue-574846800

**Comment by liuwenbo4795** [comment]
I have tried it,but it didn't work. @SamihaSara

**Comment by haishibei** [comment]
@SamihaSara ， thanks u, it works
