### ISSUE TITLE
The problem of 'siam_mask_dataset'

### ISSUE THREAD

**Issue by HaoyuanXu** [foolwood/SiamMask#144]
File "/home/shgao/track/SiamMask/datasets/siam_mask_dataset.py", line 551, in __getitem__
    search_mask = (cv2.imread(search[2], 0) > 0).astype(np.float32)
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Thank u  in advance

**Comment by xiaogeaihighying** [comment]
you can try only use ytb_vos, contact with me weixin: chuyanqiu2255

**Comment by xiaogeaihighying** [comment]
> File "/home/shgao/track/SiamMask/datasets/siam_mask_dataset.py", line 551, in **getitem**
> search_mask = (cv2.imread(search[2], 0) > 0).astype(np.float32)
> TypeError: '>' not supported between instances of 'NoneType' and 'int'
> 
> Thank u in advance

you can try only use ytb_vos, contact with me weixin: chuyanqiu2255

**Comment by haishibei** [comment]
@HaoyuanXu ， hello ,have you solved the problem?

**Comment by ahmedosamaz** [comment]
hey, did it work for you? I'm having the same error
