### ISSUE TITLE
Why is it stuck??

### ISSUE THREAD

**Issue by HaoyuanXu** [foolwood/SiamMask#147]
![image](https://user-images.githubusercontent.com/49853717/76697771-61ea4900-66d6-11ea-823c-5723fa5370a7.png)

**Comment by HaoyuanXu** [comment]
Stuck at 'eval eao' step
Thank u in advance

**Comment by kind-hearted-Tbag** [comment]
I also confronted with the same problem

**Comment by kind-hearted-Tbag** [comment]
pip install numba==0.47.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by HaoyuanXu** [comment]
Successful solution
