### ISSUE TITLE
eval eao: 0%|                                       | 0/15 [00:00<?, ?it/s]

### ISSUE THREAD

**Issue by HaoyuanXu** [foolwood/SiamMask#148]
I have been stuck in this step for a long while
How could i solve it?Thank u

**Comment by kind-hearted-Tbag** [comment]
pip install numba==0.47.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by HaoyuanXu** [comment]
Thx!!!Successfully solve it.

**Comment by Lin-Yong-code** [comment]
请问如何解决[2023-11-06 04:30:54,869-rk0-dataset.py# 52] a\ILSVRC2015_train_00000000/00 has no frames
