### ISSUE TITLE
ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by Totoro-wen** [foolwood/SiamMask#18]
Hello.
I met the following trouble when i running the demo.py, and I've made a lot of effort to solve it, but can't.
```
Traceback (most recent call last):
  File "/home/aibc/Wen/Siamese/SiamMask/tools/demo.py", line 12, in <module>
    from tools.test import siamese_track,siamese_init
ModuleNotFoundError: No module named 'tools'
```
Thanks for your help.

**Comment by Totoro-wen** [comment]
Move the tools, models, utils files under the experimental file, and import the corresponding library under demo.py.This is my first exposure to  the framework.

**Comment by foolwood** [comment]
@Totoro-wen 
I am sorry for the inconvenience caused by the framework design.
```
git clone https://github.com/foolwood/SiamMask.git && cd SiamMask
export SiamMask=$PWD
export PYTHONPATH=$SiamMask:$PYTHONPATH
```

Through this design, we can easily conduct lots of independent experiments in the `experiments` folder and keep the code clean (share tools, models, utils).

**Comment by Totoro-wen** [comment]
Thank for your reply in time.

**Comment by lzy19974** [comment]
I have met the same problem.I have tried for many times,and twice of them worked and others did not.

**Comment by tarunpulluri** [comment]
Worked

**Comment by farazBhatti** [comment]
@foolwood  ive tried your suggestion but it doesnot work.

**Comment by zzzmm1** [comment]
I have met the same problem when testing. I have tried @foolwood suggestion but failed, so try @Totoro-wen idea, then met another similar problem: FileNotFoundError : No such file or directory: 'xxx/xxx/xxx/SiamMask/experiments/siammask_sharp/data'
should I move the data file under siammask_sharp file and run in the current content?
