### ISSUE TITLE
How about the speed? Only 10fps on a Titan Xp

### ISSUE THREAD

**Issue by nigyiii** [foolwood/SiamMask#19]
Hello, I run the project with only 10 fps on a titan xp, which is much slower than mentioned in README.md. Does anyone know how to accelerate? How to achieve a speed like real-time tracking?

**Comment by drahmad89** [comment]
Hello, I have the same question too !!

**Comment by drahmad89** [comment]
comment these in demo.py:
            cv2.imshow('SiamMask', im)
            key = cv2.waitKey(1)

**Comment by SamihaSara** [comment]
@drahmad89  have you tested this model with VOT2016 dataset using this command (python ../../tools/eval.py --dataset VOT2016 --tracker_prefix C --result_dir ./test/VOT2016) ? Please let me know, I am trying to do so but facing the following error.  Did you download any tracker file to produce results?
![image](https://user-images.githubusercontent.com/9627710/72216833-8a2bbf00-3550-11ea-9022-cbcfa9680261.png)

**Comment by liuwenbo4795** [comment]
@SamihaSara ,When I finshed the vot2018's test and want to run the statement"python ../../tools/eval.py --dataset VOT2018 --tracker_prefix C --result_dir ./test/VOT2018",I met the same question with you .Have you solved the problem?
![divide by 0](https://user-images.githubusercontent.com/43468108/77393233-91d0d500-6dd7-11ea-9229-fea0695ac0a4.png)

**Comment by GOBish** [comment]
I am also getting slow results - max 8 FPS on GPU. Any advice?

**Comment by haishibei** [comment]
@liuwenbo4795 , hello, have you fixed it ?

**Comment by GOBish** [comment]
@haishibei I have not figured out a solution yet

**Comment by haishibei** [comment]
@GOBish  ok, thanks. I test it at VOT2016,the speed is  about 20fps-30fps, but I failed test it at VOT2018, and encountered the same question"divided by zero", have  you fixed it? @SamihaSara @liuwenbo4795 , waiting for your  reply, thanks
