### ISSUE TITLE
results on OTB

### ISSUE THREAD

**Issue by shallowtoil** [foolwood/SiamMask#34]
Hi, I'm wondering siammask's performance on OTB.  I evaluated on OTB100 using siammask-3B bbox branch output with siammask_vot.pth with tracking parameters same as DaSiamRPN but only got 0.629/0.844 with AUC/Prec. Is this intrinsic or because of sensitivity to the hyper-paramerters?

Thanks for your time.

**Comment by beyondpzk** [comment]
Dear shallowtoil,

How I test on OTB by this codes, thanks~
