### ISSUE TITLE
pretrained resnet wieghts

### ISSUE THREAD

**Issue by ammirato** [foolwood/SiamMask#4]
Can you share where I can access the 'resnet.model' weights, the pretrained resnet weights. And where the load_pretrain method is?

From line 37 of custom.py

**Comment by foolwood** [comment]
You can download ImageNet-1k pretrained model on [google drive](https://drive.google.com/drive/folders/1hMO2vg-s31V5tyeq7-TvdtpMdX7rexpJ?usp=sharing).

Thanks.
