### ISSUE TITLE
run demo.py "AttributeError: 'module' object has no attribute 'device'"

### ISSUE THREAD

**Issue by zhb96** [foolwood/SiamMask#43]
python ../../tools/demo.py --resume SiamMask_DAVIS.pth --config config_davis.json
Traceback (most recent call last):
  File "../../tools/demo.py", line 20, in <module>
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
AttributeError: 'module' object has no attribute 'device'

How can I solve the problem? Thank you very much.

**Comment by carvdane** [comment]
Not the author, but it seems like your environment may not be able to see your GPU devices.
I would try 'export CUDA_VISIBLE_DEVICES=0'. you can replace the '0' with whatever gpu device you want to work on. I would add this to your .bashrc so you do not have to constantly update your environment. 

Hope that helps!

**Comment by zhb96** [comment]
Thank you for your reply. I will try.
