### ISSUE TITLE
The structure of SiamRPN++ you implement is different from that in Paper.

### ISSUE THREAD

**Issue by TeslaHua** [foolwood/SiamMask#55]
Hi,Qiang
      Thks for your contribution!
       I trained and tested the SiamRPN++ network you implemented and studied the code. Some questions now:
1. The output model structure (**only layer3 in the custom version of resnet50, why?**) is different from the SiamRPN++ model in pysot.

2. SiamRPN++ indicates in paper that the feature fusion of layer2_RPN, layer3_RPN and layer4_RPN in ResNet50 is not found in your code.

 look forward to your reply.

**Comment by luoshanwei** [comment]
I have the same questions

**Comment by foolwood** [comment]
because in my paper, I only compare with layer 3 version of SiamRPN. 
(SiamMask only use ResNet feature from layer 3).

If you want to reimplement original version of SiamRPN++, please refer [pysot](https://github.com/STVIR/pysot/).
