### ISSUE TITLE
no checkpoint.pth is made 

### ISSUE THREAD

**Issue by seokhyeonSong** [foolwood/SiamMask#68]
Hi. Thanks for sharing good code!!

I'm trying to run this code.

I didn't download the det data file yet and other data files is downloaded

so I deleted about det file from config.json

And i tried to bash run.sh

but it makes two errors..

1. args.resume >> It doesn't make checkpoint_e09.pth 

it says {} is not a valid file

2. after i made 1.error import numpy makes error with there's no module numpy but i have..

It would be thankful if you can give a solution about this error!

**Comment by gyftsy** [comment]
hi! how u fix it?i meet the same error with u
