### ISSUE TITLE
about Youtube-VOS dataset

### ISSUE THREAD

**Issue by zhenzhen2017** [foolwood/SiamMask#69]
Is there anyone who can help me to upload Youtube-VOS dataset to Baidu?
https://youtube-vos.org/dataset/download ,The site configured at this address does not contain the requested file.

**Comment by QIQIVTrackingY** [comment]
Do you download Youtube-VOS dataset sucessfully?

**Comment by LANMNG** [comment]
I download youtube-VOS succesfully,but when i evaluate on the valid set ,it has the error

**Comment by QIQIVTrackingY** [comment]
Can you share the dataset with BaiduDrive? I am not able to download it from Google Drive. Thank you！



---Original---

**Comment by zhenzhen2017** [comment]
I still can not download youtube-VOS.
