### ISSUE TITLE
where can we download dataset ytb-bb?

### ISSUE THREAD

**Issue by zhenzhen2017** [foolwood/SiamMask#70]
/SiamMask_VOT_LD.pth
-LD means training with large dataset (ytb-bb+ytb-vos+vid+coco+det).

my questions:
(1) SiamMask_VOT_LD.pth is  trained with the following five dataset: (a) ytb-bb (b)ytb-vos (c)vid (d)coco (e)det ?
(2) where can we download dataset ytb-bb?
thanks for helping!

**Comment by ahmedosamaz** [comment]
> 
> 
> /SiamMask_VOT_LD.pth
> -LD means training with large dataset (ytb-bb+ytb-vos+vid+coco+det).
> 
> my questions:
> (1) SiamMask_VOT_LD.pth is trained with the following five dataset: (a) ytb-bb (b)ytb-vos (c)vid (d)coco (e)det ?
> (2) where can we download dataset ytb-bb?
> thanks for helping!

you can download it from here https://research.google.com/youtube-bb/download.html
