### ISSUE TITLE
How can I execute SiamMask with my own video

### ISSUE THREAD

**Issue by seokhyeonSong** [foolwood/SiamMask#71]
Hi. thanks for sharing amazing code!

I'm a student who just started to study learning.

I saw this on paperswithcode and got to execute this code.

I've followed your directions until training and I finally made my own training set ~~.pth

I want to execute this code with my own video.

It seems to be executed with several frames of video with a json file.

But I don't know how to make frames with video or make json file cuz I'm noob... TT

Can you please tell me how to execute this code with my own video?

**Comment by henbucuoshanghai** [comment]
how to solve it?????????????????
